name: Docker Image CI

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      misp_ref:
        description: 'MISP branch or tag to build'
        required: true
        default: '2.4'

env:
  # See https://github.com/goodwithtech/dockle/issues/188
  DOCKLE_HOST: "unix:///var/run/docker.sock"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    -
      name: Fetch variables
      run: python3 .github/workflows/docker-version.py ${{ github.event.inputs.misp_ref }}
      id: variables
    -
      name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-
    -
      name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: misp:${{ github.event.inputs.misp_ref }}
        cache-from: type=local,src=/tmp/.buildx-cache/amd64
        cache-to: type=local,dest=/tmp/.buildx-cache-new/amd64,mode=max
        build-args: |
          CACHEBUST=${{ steps.variables.outputs.MISP_COMMIT }}
          MISP_VERSION=${{ steps.variables.outputs.MISP_VERSION }}
    -
      name: Login to GitHub Container Registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push version to test
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/misp:${{ steps.variables.outputs.MISP_COMMIT }}
        build-args: |
          CACHEBUST=${{ steps.variables.outputs.MISP_COMMIT }}
          MISP_VERSION=${{ steps.variables.outputs.MISP_VERSION }}
    -
      name: Test
      run: |
        docker history misp:${{ steps.variables.outputs.MISP_COMMIT }}
        MISP_IMAGE=misp:${{ steps.variables.outputs.MISP_COMMIT }} docker compose --verbose up --detach --quiet-pull --wait --wait-timeout 130
        docker logs misp
        AUTHKEY=$(docker exec misp su-exec apache /var/www/MISP/app/Console/cake user init)
        VERSION=$(curl --fail -v -H "Authorization: $AUTHKEY" -H "Accept: application/json" http://localhost:8080/servers/getVersion)
        echo $VERSION | jq
        docker compose down
    -
      name: Container scan
      uses: azure/container-scan@v0
      with:
        image-name:  ghcr.io/${{ github.repository_owner }}/misp:${{ steps.variables.outputs.MISP_COMMIT }}
        severity-threshold: CRITICAL
    -
      # Temp fix
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
        du -sh /tmp/.buildx-cache
    -
      name: Build and push as latest
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/misp:latest
        build-args: |
          CACHEBUST=${{ steps.variables.outputs.MISP_COMMIT }}
          MISP_VERSION=${{ steps.variables.outputs.MISP_VERSION }}
